### ISSUE TITLE
Can't link user

### ISSUE THREAD

**Issue by blueperil** [icewind1991/mx-puppet-steam#13]
I have tried to link my Steam user to the puppet, but I get the following message:
> Dec-30 16:08:48.753 [bot-sdk-Appservice] info: Processing event of type m.room.message
> 127.0.0.1 - - [30/Dec/2020:15:08:48 +0000] "PUT /transactions/44?access_token=0b34f58f-d41e-4623-9691-091aafc105f5 HTTP/1.1" 200 2 "-" "Synapse/1.24.0"
> Dec-30 16:08:48.765 [BotProvisioner] info: Got message to process with arg=link
> Dec-30 16:08:48.767 [MatrixEventHandler] error: Error handling appservice room.event TypeError ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
>     at validateString (internal/validators.js:120:11)
>     at Object.join (path.js:1039:7)
>     at userData (/usr/lib/node_modules/mx-puppet-steam/node_modules/appdirectory/lib/appdirectory.js:21:29)
>     at AppDirectory._setTemplates (/usr/lib/node_modules/mx-puppet-steam/node_modules/appdirectory/lib/appdirectory.js:134:34)
>     at new AppDirectory (/usr/lib/node_modules/mx-puppet-steam/node_modules/appdirectory/lib/appdirectory.js:129:10)
>     at new SteamUser (/usr/lib/node_modules/mx-puppet-steam/node_modules/steam-user/index.js:83:35)
>     at /usr/lib/node_modules/mx-puppet-steam/index.js:115:28
>     at Generator.next (<anonymous>)
>     at /usr/lib/node_modules/mx-puppet-steam/index.js:8:71
>     at new Promise (<anonymous>) {
>   code: 'ERR_INVALID_ARG_TYPE'
> }

**Comment by blueperil** [comment]
Some environment variables were not set: XDG_DATA_HOME, XDG_CACHE_HOME, XDG_DATA_DIRS, XDG_CONFIG_HOME or HOME.
With these variables the app is starting and I can link my steam profile
