### ISSUE TITLE
Unable to correct password error, Relink command does not work as expected

### ISSUE THREAD

**Issue by Cerothen** [icewind1991/mx-puppet-steam#2]
Received a note that my bridge is disconected:
![image](https://user-images.githubusercontent.com/9008757/87599208-7577e180-c6c1-11ea-88c1-d353603d5f0a.png)

There doesn't appear to be a way to resolve the issue. The relink command makes a new indexed bridge (likely not the intended design) and the link command is for new bridges also. 
 Any advise so my rooms don't all have to be remade?

**Comment by IngwiePhoenix** [comment]
Having this issue myself:

```
Aug-25 22:02:41.153 [bot-sdk-MatrixLiteClient] info: (REQ-7) PUT http://localhost:8008/_matrix/client/r0/rooms/!UUKBcjSGPGDklEECqq%3Aingwie.io/send/m.room.message/1598392961153__REQ6
Aug-25 22:02:41.430 [MatrixPuppet:Steam] error: Failed to start up puppet 1 Error: InvalidPassword
    at SteamUser.<anonymous> (/srv/matrix/steam/node_modules/steam-user/components/logon.js:468:16)
    at /srv/matrix/steam/node_modules/steam-user/components/classes/HandlerManager.js:37:12
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (/srv/matrix/steam/node_modules/steam-user/components/classes/HandlerManager.js:36:12)
    at SteamUser._handleMessage (/srv/matrix/steam/node_modules/steam-user/components/messages.js:545:24)
    at SteamUser._handleNetMessage (/srv/matrix/steam/node_modules/steam-user/components/messages.js:480:7)
    at SteamUser.processMulti (/srv/matrix/steam/node_modules/steam-user/components/messages.js:572:9)
    at SteamUser.<anonymous> (/srv/matrix/steam/node_modules/steam-user/components/messages.js:566:16)
    at /srv/matrix/steam/node_modules/steam-user/components/classes/HandlerManager.js:37:12
    at Array.forEach (<anonymous>) {
  eresult: 5
}
```

My password is definitively correct and it had asked me for my Steam Guard code too. I verified the used password in a browser, just to double-check. No luck unfortunately.

**Comment by GrimKriegor** [comment]
Same here on `91d5de6c2cac07fb57e8fcfed8768b8ac17a2877`.

```
Sep-4 11:35:55.931 [MatrixPuppet:Steam] error: Failed to start up puppet 4 Error: InvalidPassword
```

Issued the link command, received the Steam guard code via email and sent it to the bot.

**Comment by chauffer** [comment]
Same here, although there have been no new commits since last comment, this project seems unfortunately unmaintained.

**Comment by wvffle** [comment]
And the same happened here ;/

**Comment by deepbluev7** [comment]
Okay, I made some (small) progress on this:

relink does work, but it defaults to reusing the existing sentry file, which is stored in `~/.local/share/node-user/sentry.${accountName}.bin`. Deleting this does not fix my connection errors, but it at least prompts me for the steam guard again.

It seems like there is some issue, when using Email for Steam Guard, see here: https://github.com/DoctorMcKay/node-steam-user/issues/333

**Comment by JokerGermany** [comment]
I have he same problem.
I link the account enter the steam guard code and after this i get a new email from Steam with exact the same SteamGuard Code.
When i restart mx-puppet-steam `systemctl restart matrix-mx-puppet-steam` i get this error:
`Jul 28 00:46:35 nas matrix-mx-puppet-steam[15650]: Jul-27 22:46:35.168 [MatrixPuppet:Steam] error: Failed to start up puppet 4 Error: InvalidPassword
Jul 28 00:46:35 nas matrix-mx-puppet-steam[15650]:     at SteamUser.<anonymous> (/opt/mx-puppet-steam/node_modules/steam-user/components/logon.js:489:16)
Jul 28 00:46:35 nas matrix-mx-puppet-steam[15650]:     at /opt/mx-puppet-steam/node_modules/steam-user/components/classes/HandlerManager.js:37:12
Jul 28 00:46:35 nas matrix-mx-puppet-steam[15650]:     at Array.forEach (<anonymous>)
Jul 28 00:46:35 nas matrix-mx-puppet-steam[15650]:     at HandlerManager.emit (/opt/mx-puppet-steam/node_modules/steam-user/components/classes/HandlerManager.js:36:12)
Jul 28 00:46:35 nas matrix-mx-puppet-steam[15650]:     at SteamUser._handleMessage (/opt/mx-puppet-steam/node_modules/steam-user/components/messages.js:571:24)
Jul 28 00:46:35 nas matrix-mx-puppet-steam[15650]:     at SteamUser._handleNetMessage (/opt/mx-puppet-steam/node_modules/steam-user/components/messages.js:506:7)
Jul 28 00:46:35 nas matrix-mx-puppet-steam[15650]:     at SteamUser.processMulti (/opt/mx-puppet-steam/node_modules/steam-user/components/messages.js:598:9)
Jul 28 00:46:35 nas matrix-mx-puppet-steam[15650]:     at SteamUser.<anonymous> (/opt/mx-puppet-steam/node_modules/steam-user/components/messages.js:592:16)
Jul 28 00:46:35 nas matrix-mx-puppet-steam[15650]:     at /opt/mx-puppet-steam/node_modules/steam-user/components/classes/HandlerManager.js:37:12
Jul 28 00:46:35 nas matrix-mx-puppet-steam[15650]:     at Array.forEach (<anonymous>) {
Jul 28 00:46:35 nas matrix-mx-puppet-steam[15650]:   eresult: 5
Jul 28 00:46:35 nas matrix-mx-puppet-steam[15650]: }
`
and Steam sends a new SteamGuard Code.

@icewind1991 pls help

**Comment by deepbluev7** [comment]
Yes, if you use the app for 2FA, you shouldn't have any issues, but I can't use the app, so this solution doesn't work for me (unless I set up an Android VM).

**Comment by corincorvus** [comment]
I use 2FA and have the same Problem on my Server.

![grafik](https://user-images.githubusercontent.com/21257329/144279679-c89011c4-61f4-406d-8aa8-146f0779898c.png)
Relink is not usable
I have to unlink and link my account again every week. not comfotable.

**Comment by zippyy** [comment]
same thing happening to me 
i can not link with or without steam guard

**Comment by UmbraChimera** [comment]
Tried using this with mobile 2fa, and still not working. Is there any working solution on this?

**Comment by roughnecks** [comment]
Invalid password for me too. I'm using WinAuth and my password is definitely correct.

**Comment by nexusVI** [comment]
I am seeing the same issue.

**Comment by plantroon** [comment]
Same problem, using the guard OTP from Bitwarden, same as in mobile app (or winauth and similar apps)
