### ISSUE TITLE
Not receiving messages

### ISSUE THREAD

**Issue by HarHarLinks** [icewind1991/mx-puppet-steam#23]
I'm using https://github.com/spantaleev/matrix-docker-ansible-deploy with this bridge.
I have linked it and entered a steam guard code.
I am not receiving any messages, nor does listusers show any of my friends (as it does with mx-puppet-discord).
However I am sporadically receiving new steam guard requests to my email, so I suspect the linking isn't working after all.

**Comment by HarHarLinks** [comment]
I think the following is just an unhandled exception with wrong number of arguments for `relink` (no arguments provided).
```
Nov 01 13:26:48 hostname matrix-mx-puppet-steam[1236165]: Nov-1 12:26:48.688 [BotProvisioner] info: Got message to process with arg=relink
Nov 01 13:26:48 hostname matrix-mx-puppet-steam[1236165]: Nov-1 12:26:48.690 [MatrixEventHandler] error: Error handling appservice room.event error: invalid input syntax for type integer: "NaN"
Nov 01 13:26:48 hostname matrix-mx-puppet-steam[1236165]:     at Parser.parseErrorMessage (/opt/mx-puppet-steam/node_modules/pg-protocol/dist/parser.js:278:15)
Nov 01 13:26:48 hostname matrix-mx-puppet-steam[1236165]:     at Parser.handlePacket (/opt/mx-puppet-steam/node_modules/pg-protocol/dist/parser.js:126:29)
Nov 01 13:26:48 hostname matrix-mx-puppet-steam[1236165]:     at Parser.parse (/opt/mx-puppet-steam/node_modules/pg-protocol/dist/parser.js:39:38)
Nov 01 13:26:48 hostname matrix-mx-puppet-steam[1236165]:     at Socket.<anonymous> (/opt/mx-puppet-steam/node_modules/pg-protocol/dist/index.js:10:42)
Nov 01 13:26:48 hostname matrix-mx-puppet-steam[1236165]:     at Socket.emit (node:events:379:20)
Nov 01 13:26:48 hostname matrix-mx-puppet-steam[1236165]:     at addChunk (node:internal/streams/readable:313:12)
Nov 01 13:26:48 hostname matrix-mx-puppet-steam[1236165]:     at readableAddChunk (node:internal/streams/readable:288:9)
Nov 01 13:26:48 hostname matrix-mx-puppet-steam[1236165]:     at Socket.Readable.push (node:internal/streams/readable:227:10)
Nov 01 13:26:48 hostname matrix-mx-puppet-steam[1236165]:     at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
Nov 01 13:26:48 hostname matrix-mx-puppet-steam[1236165]:   length: 108,
Nov 01 13:26:48 hostname matrix-mx-puppet-steam[1236165]:   severity: 'ERROR',
Nov 01 13:26:48 hostname matrix-mx-puppet-steam[1236165]:   code: '22P02',
Nov 01 13:26:48 hostname matrix-mx-puppet-steam[1236165]:   detail: undefined,
Nov 01 13:26:48 hostname matrix-mx-puppet-steam[1236165]:   hint: undefined,
Nov 01 13:26:48 hostname matrix-mx-puppet-steam[1236165]:   position: '44',
Nov 01 13:26:48 hostname matrix-mx-puppet-steam[1236165]:   internalPosition: undefined,
Nov 01 13:26:48 hostname matrix-mx-puppet-steam[1236165]:   internalQuery: undefined,
Nov 01 13:26:48 hostname matrix-mx-puppet-steam[1236165]:   where: undefined,
Nov 01 13:26:48 hostname matrix-mx-puppet-steam[1236165]:   schema: undefined,
Nov 01 13:26:48 hostname matrix-mx-puppet-steam[1236165]:   table: undefined,
Nov 01 13:26:48 hostname matrix-mx-puppet-steam[1236165]:   column: undefined,
Nov 01 13:26:48 hostname matrix-mx-puppet-steam[1236165]:   dataType: undefined,
Nov 01 13:26:48 hostname matrix-mx-puppet-steam[1236165]:   constraint: undefined,
Nov 01 13:26:48 hostname matrix-mx-puppet-steam[1236165]:   file: 'numutils.c',
Nov 01 13:26:48 hostname matrix-mx-puppet-steam[1236165]:   line: '320',
Nov 01 13:26:48 hostname matrix-mx-puppet-steam[1236165]:   routine: 'pg_strtoint32'
Nov 01 13:26:48 hostname matrix-mx-puppet-steam[1236165]: }
```

**Comment by RoiArthurB** [comment]
I had the same problem, my dirty solution is to disable SteamGuard :disappointed: 
I think the problem is that the puppet doesn't keep alive the connection and doesn't submit the good code at the good instance (that's why you receive new mail every time, Steam didn't save the puppet instance as valid) 🤔

**Comment by Traace** [comment]
I have the same problem, but with more than 300 games I dislike to disable SteamGuard. 😶‍🌫️
