### ISSUE TITLE
Error generating an appservice registration file !!

### ISSUE THREAD

**Issue by raymand211092** [icewind1991/mx-puppet-steam#30]
> mx-puppet-steam@0.0.0 build /root/mx-puppet-steam
> tsc

/root/mx-puppet-steam/node_modules/command-line-args/dist/index.js:1345
        throw err
        ^

UNKNOWN_VALUE: Unknown value: [-c
    at commandLineArgs (/root/mx-puppet-steam/node_modules/command-line-args/dist/index.js:1342:21)
    at Object.<anonymous> (/root/mx-puppet-steam/build/index.js:33:4)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  value: '[-c'
}

My node version its 14.19.1

**Comment by raymand211092** [comment]
Its solved !!!
